version: "3"

services:
  app:
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:34.201.63.194"

  reverse-proxy:
    image: traefik:v1.7.11-alpine
    command: --api --docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    api:
        image: desenvolvedorio/api-aspnet-curso-angular:latest
        container_name: api-aspnet-curso-angular        
        ports:
            - "5001:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - db
    db:
        image: desenvolvedorio/sql-api-curso-angular:latest
        container_name: sql-api-curso-angular
        ports:  
            - "1433:1433"
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"
